version: "2"
services:
  naivefront:
    image: rlkamradt/naivefront
    networks:
      - network
    volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf
     - ~/.secret:/etc/certs
    ports:
     - "443:443"
  naiveuser:
    image: rlkamradt/naiveuser
    networks:
     - network
  redis:
    image: redis:alpine
    networks:
      - network
  naivecoin:
    image: rlkamradt/naivecoin
    environment:
     - NAME=1
     - HOST=0.0.0.0
    volumes:
     - ./:/naivecoin
    networks:
     - network
networks:
  network:
